# Generated by Django 5.0.3 on 2024-03-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbyte_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Student_year',
            field=models.CharField(default='2024', max_length=20),
        ),
    ]
