# Generated by Django 5.0.3 on 2024-03-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbyte_api', '0004_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Student_year',
            field=models.CharField(max_length=20),
        ),
    ]
