# Generated by Django 5.0.3 on 2024-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbyte_api', '0005_alter_game_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Student_year',
            field=models.CharField(default='2024', max_length=20),
        ),
    ]
